{{- if .Values.kyvernoPolicy.blockUpdateResource -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  {{- with .Values.kyvernoConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    policies.kyverno.io/title: Block Delete Kubernetes Resources
    policies.kyverno.io/category: Standard
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: This policy restricts updates to resources.
  {{- end }}
  name: validating-block-update-resource
spec:
  validationFailureAction: {{ .Values.kyvernoConfig.validationFailureAction }}
  # check exist resource
  background: {{ .Values.kyvernoConfig.background }}
  rules:
  - name: block-update-resource
    match:
      any:
      - resources:
          kinds:
          - Secret
          - NetworkPolicy 
          - IngressClass
    validate:
      deny:
        conditions:
          any:
          - key: {{ .Values.kyvernoConfig.conditionskey }}
            operator: AnyIn
            value:
            - UPDATE
      message: |
        .
        =============================================================================================
        [ClusterPolicy/Validating/block-update-resource]
        This policy restricts updates to Secret, NetworkPolicy, IngressClass resources.

        Information :
          This Cluster has policies applied using Kyverno.
          Kyverno is a policy engine for Kubernetes that allows you to enforce custom policies.

          We are applying policies such as preventing the deletion of all namespaces,
          blocking the removal of resources with specific labels, and restricting the ImagePullPolicy.

          If you would like to know more details, Please seek a Admin. (email : ckops@sk.com)
        =============================================================================================
        .
{{- end }}
